using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using System.IO;
using System.Data.SQLite;

namespace NURSAN_PROJE
{
    public partial class Projectwindow : DevExpress.XtraBars.ToolbarForm.ToolbarForm
    {
        public Projectwindow()
        {
           
            this.Hide();
            InitializeComponent();
            new Form1().ShowDialog();
            this.Show();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void GridControl1_Click(object sender, EventArgs e)
        {

        }

        private void TableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {
            
        }

        private void CheckButton1_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void SimpleButton3_Click(object sender, EventArgs e)
        {

        }

        private void LabelControl6_Click(object sender, EventArgs e)
        {

        }

        private void SidePanel1_Click(object sender, EventArgs e)
        {

        }

        private void GridControl2_Click(object sender, EventArgs e)
        {

        }

        private void LabelControl12_Click(object sender, EventArgs e)
        {

        }

        private void LabelControl13_Click(object sender, EventArgs e)
        {

        }

        private void GridControl3_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButton1_Click(object sender, EventArgs e)
        {
            DataTable table1 = new DataTable("Connections");

            table1.Columns.Add("Soket");
            table1.Columns.Add("Pin");
            table1.Columns.Add("Test noktası");
            table1.Rows.Add("Soket-3","1", "1");
            table1.Rows.Add("Soket-3", "2", "1");
            table1.Rows.Add("Soket-3", "3", "2");


            gridControl3.DataSource = table1;
            Console.WriteLine("test");
        }

        private void Projectwindow_Load(object sender, EventArgs e)
        {
            sqlDataSource1.ConnectionParameters.Equals(Application.StartupPath + "\\database.db");
        }
    }
}


